In [0]:
#Numpy -
import numpy as np

In [0]:
#array(),arange(),reshape(),sum(),mean(),max(),min(),std(),argmax(),argmin()
#shape,ndim,size

In [0]:
a = np.array([4,6,8,9,3])
print(a)
print(a.shape)
print(a.ndim)
print(a.size)

[4 6 8 9 3]
(5,)
1
5


In [0]:
a = np.array([[4,6,8,9,3],[11,12,13,56,78],[45,67,34,12,56]])
print(a)
print(a.shape)
print(a.ndim)
print(a.size)

[[ 4  6  8  9  3]
 [11 12 13 56 78]
 [45 67 34 12 56]]
(3, 5)
2
15


In [0]:
b = np.arange(0,36).reshape(3,4,3)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [0]:
x1 = np.random.randint(2,20,15)
x2 = np.random.randint(3,30,15)
x3 = np.random.randint(7,25,15)

In [0]:
X = np.array([x1,x2,x3])
X

array([[17,  9,  2,  6, 16, 18, 10, 11, 17,  7, 16, 16, 14,  2,  3],
       [24, 26, 21,  6, 22,  6,  7, 23, 21, 27, 27, 28, 19,  3,  6],
       [10, 23, 11, 14, 14, 20, 14, 23, 23, 22,  9, 11, 15, 11, 22]])

In [0]:
np.transpose(X)

array([[17, 24, 10],
       [ 9, 26, 23],
       [ 2, 21, 11],
       [ 6,  6, 14],
       [16, 22, 14],
       [18,  6, 20],
       [10,  7, 14],
       [11, 23, 23],
       [17, 21, 23],
       [ 7, 27, 22],
       [16, 27,  9],
       [16, 28, 11],
       [14, 19, 15],
       [ 2,  3, 11],
       [ 3,  6, 22]])

In [0]:
X.reshape(15,3)

array([[17,  9,  2],
       [ 6, 16, 18],
       [10, 11, 17],
       [ 7, 16, 16],
       [14,  2,  3],
       [24, 26, 21],
       [ 6, 22,  6],
       [ 7, 23, 21],
       [27, 27, 28],
       [19,  3,  6],
       [10, 23, 11],
       [14, 14, 20],
       [14, 23, 23],
       [22,  9, 11],
       [15, 11, 22]])

In [0]:
k = np.random.randn(3)
k

array([ 0.34915113, -0.42280951, -0.07797823])

In [0]:
l = np.random.rand(3)
l

array([0.77455244, 0.19171886, 0.75997757])

In [0]:
a

array([[ 4,  6,  8,  9,  3],
       [11, 12, 13, 56, 78],
       [45, 67, 34, 12, 56]])

In [0]:
#row slicing , column slicing
a[0:2 ,:]

array([[ 4,  6,  8,  9,  3],
       [11, 12, 13, 56, 78]])

In [0]:
a[:,2:4]

array([[ 8,  9],
       [13, 56],
       [34, 12]])

In [0]:
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [0]:
print(np.sum(a))
print(np.max(a))
print(np.min(a))
print(np.std(a))
print(np.argmax(a))
print(np.argmin(a))
print(np.mean(a))

414
78
3
25.011464038183238
9
4
27.6


In [0]:
a

array([[ 4,  6,  8,  9,  3],
       [11, 12, 13, 56, 78],
       [45, 67, 34, 12, 56]])

In [0]:
#Dot product
#Combing two different matrices

In [0]:
a

array([[ 4,  6,  8,  9,  3],
       [11, 12, 13, 56, 78],
       [45, 67, 34, 12, 56]])

In [0]:
b = np.arange(0,5).reshape(5,1)
b

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [0]:
np.dot(a,b)
np.matmul(a,b)

array([[ 61],
       [518],
       [395]])

In [0]:
#Stacking
a

array([[ 4,  6,  8,  9,  3],
       [11, 12, 13, 56, 78],
       [45, 67, 34, 12, 56]])

In [0]:
c = np.arange(20).reshape(4,5)
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [0]:
z = np.vstack((a,c))

In [0]:
d = np.arange(3).reshape(3,1)
d

array([[0],
       [1],
       [2]])

In [0]:
np.hstack((a,d))

array([[ 4,  6,  8,  9,  3,  0],
       [11, 12, 13, 56, 78,  1],
       [45, 67, 34, 12, 56,  2]])

In [0]:
z

array([[ 4,  6,  8,  9,  3],
       [11, 12, 13, 56, 78],
       [45, 67, 34, 12, 56],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [0]:
z[:,-2:]

array([[ 9,  3],
       [56, 78],
       [12, 56],
       [ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19]])

In [0]:
print(np.zeros([3,3]))
print(np.ones([3,3]))
print(np.eye(3))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [0]:
#Pandas - Access, Analyse, preprocess over data
import pandas as pd

In [0]:
#DataFrame
p = pd.DataFrame(z,columns=['a','b','c','d','e'])
p

a   b   c   d   e
0   4   6   8   9   3
1  11  12  13  56  78
2  45  67  34  12  56
3   0   1   2   3   4
4   5   6   7   8   9
5  10  11  12  13  14
6  15  16  17  18  19

In [0]:
p[['a','b','c']]

a   b   c
0   4   6   8
1  11  12  13
2  45  67  34
3   0   1   2
4   5   6   7
5  10  11  12
6  15  16  17

In [0]:
#loc
#iloc
p.loc[0:4,'c':'e']

c   d   e
0   8   9   3
1  13  56  78
2  34  12  56
3   2   3   4
4   7   8   9

In [0]:
p.iloc[0:4,2:4]

c   d
0   8   9
1  13  56
2  34  12
3   2   3

In [0]:
chips = pd.read_table('http://bit.ly/chiporders')

In [0]:
chips

order_id  ...  item_price
0            1  ...      $2.39 
1            1  ...      $3.39 
2            1  ...      $3.39 
3            1  ...      $2.39 
4            2  ...     $16.98 
...        ...  ...         ...
4617      1833  ...     $11.75 
4618      1833  ...     $11.75 
4619      1834  ...     $11.25 
4620      1834  ...      $8.75 
4621      1834  ...      $8.75 

[4622 rows x 5 columns]

In [0]:
#Extract all the data with Chicken is present as their item name
#Calculate mean price of all the item prices
#Find out if there is any missing value present

In [0]:
#1. Find out the data types in dataframe
#2. Find out if there is any missing value

In [0]:
chips.dtypes
chips.shape

(4622, 5)

In [0]:
chips.isnull().sum()

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

In [0]:
chips['choice_description']
chips_new = chips.drop(['choice_description'],axis=1)

In [0]:
chips.head(5)

order_id  ...  item_price
0         1  ...      $2.39 
1         1  ...      $3.39 
2         1  ...      $3.39 
3         1  ...      $2.39 
4         2  ...     $16.98 

[5 rows x 5 columns]

In [0]:
chips_new

order_id  quantity                              item_name item_price
0            1         1           Chips and Fresh Tomato Salsa     $2.39 
1            1         1                                   Izze     $3.39 
2            1         1                       Nantucket Nectar     $3.39 
3            1         1  Chips and Tomatillo-Green Chili Salsa     $2.39 
4            2         2                           Chicken Bowl    $16.98 
...        ...       ...                                    ...        ...
4617      1833         1                          Steak Burrito    $11.75 
4618      1833         1                          Steak Burrito    $11.75 
4619      1834         1                     Chicken Salad Bowl    $11.25 
4620      1834         1                     Chicken Salad Bowl     $8.75 
4621      1834         1                     Chicken Salad Bowl     $8.75 

[4622 rows x 4 columns]

In [0]:
chips_new2 = chips.dropna()

In [0]:
chips.isnull().sum()

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

In [0]:
print(chips_new.isnull().sum())
print(chips_new.shape)

order_id      0
quantity      0
item_name     0
item_price    0
dtype: int64
(4622, 4)


In [0]:
print(chips_new2.isnull().sum())
print(chips_new2.shape)

order_id              0
quantity              0
item_name             0
choice_description    0
item_price            0
dtype: int64
(3376, 5)


In [0]:
chips['choice_description'].fillna('abcde',inplace=True)

In [0]:
chips

order_id  ...  item_price
0            1  ...      $2.39 
1            1  ...      $3.39 
2            1  ...      $3.39 
3            1  ...      $2.39 
4            2  ...     $16.98 
...        ...  ...         ...
4617      1833  ...     $11.75 
4618      1833  ...     $11.75 
4619      1834  ...     $11.25 
4620      1834  ...      $8.75 
4621      1834  ...      $8.75 

[4622 rows x 5 columns]

In [0]:
chips['item_price'].sum()

'$2.39 $3.39 $3.39 $2.39 $16.98 $10.98 $1.69 $11.75 $9.25 $9.25 $4.45 $8.75 $8.75 $11.25 $4.45 $2.39 $8.49 $8.49 $2.18 $8.75 $4.45 $8.99 $3.39 $10.98 $3.39 $2.39 $8.49 $8.99 $1.09 $8.49 $2.39 $8.99 $1.69 $8.99 $1.09 $8.75 $8.75 $4.45 $2.95 $11.75 $2.15 $4.45 $11.25 $11.75 $8.75 $10.98 $8.99 $3.39 $8.99 $3.99 $8.99 $2.18 $10.98 $1.09 $8.99 $2.39 $9.25 $11.25 $11.75 $2.15 $4.45 $9.25 $11.25 $8.75 $8.99 $8.99 $3.39 $8.99 $10.98 $8.99 $1.69 $8.99 $3.99 $8.75 $4.45 $8.75 $8.75 $2.15 $8.75 $11.25 $2.15 $9.25 $8.75 $8.75 $9.25 $8.49 $8.99 $1.09 $9.25 $2.95 $11.75 $11.75 $9.25 $11.75 $4.45 $9.25 $4.45 $11.75 $8.75 $8.75 $4.45 $8.99 $8.99 $3.99 $8.49 $3.39 $8.99 $1.09 $9.25 $4.45 $8.75 $2.95 $4.45 $2.39 $8.49 $8.99 $8.49 $1.09 $8.99 $3.99 $8.75 $9.25 $4.45 $11.25 $4.45 $8.99 $1.09 $9.25 $2.95 $4.45 $11.75 $4.45 $8.49 $2.39 $10.98 $22.50 $11.75 $4.45 $11.25 $4.45 $11.25 $4.45 $11.25 $11.25 $11.75 $9.25 $4.45 $11.48 $17.98 $1.69 $17.50 $4.45 $8.49 $2.39 $17.50 $4.45 $4.45 $11.25 $11.75 $10.98 $8.

In [0]:
chips['item_price'].str.replace('$','').astype(float).mean()

7.464335785374397

In [0]:
#.str.replace() - it is used to replace certain value in a pandas series
#.str.contains() - to verify certain string in a pandas series
#.astype()
#.dtypes

In [0]:
#Data filtering
chips['item_name'].str.contains('Chicken').sum()

1560

In [0]:
chips[chips['item_name'].str.contains('Chicken')]

order_id  ...  item_price
4            2  ...     $16.98 
5            3  ...     $10.98 
11           6  ...      $8.75 
12           6  ...      $8.75 
13           7  ...     $11.25 
...        ...  ...         ...
4604      1828  ...      $8.75 
4615      1832  ...      $8.75 
4619      1834  ...     $11.25 
4620      1834  ...      $8.75 
4621      1834  ...      $8.75 

[1560 rows x 5 columns]

In [0]:
chips[chips['quantity'] == 2]

order_id  ...  item_price
4            2  ...     $16.98 
18           9  ...      $2.18 
51          23  ...      $2.18 
135         60  ...     $22.50 
148         67  ...     $17.98 
...        ...  ...         ...
4435      1767  ...     $17.50 
4499      1789  ...      $2.50 
4560      1812  ...      $2.50 
4561      1813  ...     $17.50 
4582      1822  ...      $3.00 

[224 rows x 5 columns]

In [0]:
import pandas as pd
ipl = pd.read_csv(r'matches.csv')

In [0]:
#ipl = pd.read_csv(r'D:\myfolder\matches.csv')

In [0]:
ipl.head(5)

id  season       city  ...         umpire1        umpire2 umpire3
0   1    2017  Hyderabad  ...     AY Dandekar       NJ Llong     NaN
1   2    2017       Pune  ...  A Nand Kishore         S Ravi     NaN
2   3    2017     Rajkot  ...     Nitin Menon      CK Nandan     NaN
3   4    2017     Indore  ...    AK Chaudhary  C Shamshuddin     NaN
4   5    2017  Bangalore  ...             NaN            NaN     NaN

[5 rows x 18 columns]

In [0]:
ipl['city'].value_counts()

Mumbai            85
Bangalore         66
Kolkata           61
Delhi             60
Hyderabad         49
Chennai           48
Chandigarh        46
Jaipur            33
Pune              32
Durban            15
Ahmedabad         12
Centurion         12
Visakhapatnam     11
Rajkot            10
Dharamsala         9
Johannesburg       8
Cape Town          7
Port Elizabeth     7
Abu Dhabi          7
Cuttack            7
Ranchi             7
Sharjah            6
Raipur             6
Indore             5
Kochi              5
Kanpur             4
East London        3
Nagpur             3
Kimberley          3
Bloemfontein       2
Name: city, dtype: int64

In [0]:
ipl['city'].unique()

array(['Hyderabad', 'Pune', 'Rajkot', 'Indore', 'Bangalore', 'Mumbai',
       'Kolkata', 'Delhi', 'Chandigarh', 'Kanpur', 'Jaipur', 'Chennai',
       'Cape Town', 'Port Elizabeth', 'Durban', 'Centurion',
       'East London', 'Johannesburg', 'Kimberley', 'Bloemfontein',
       'Ahmedabad', 'Cuttack', 'Nagpur', 'Dharamsala', 'Kochi',
       'Visakhapatnam', 'Raipur', 'Ranchi', 'Abu Dhabi', 'Sharjah', nan],
      dtype=object)

In [0]:
len(ipl['city'].unique())

31

In [0]:
len(ipl)

636

In [0]:
ipl['win_by_runs'].idxmax()

43

In [0]:
ipl.iloc[43]['winner']

'Mumbai Indians'

In [0]:
ipl.iloc[43]

id                               44
season                         2017
city                          Delhi
date                     2017-05-06
team1                Mumbai Indians
team2              Delhi Daredevils
toss_winner        Delhi Daredevils
toss_decision                 field
result                       normal
dl_applied                        0
winner               Mumbai Indians
win_by_runs                     146
win_by_wickets                    0
player_of_match         LMP Simmons
venue              Feroz Shah Kotla
umpire1                 Nitin Menon
umpire2                   CK Nandan
umpire3                         NaN
Name: 43, dtype: object

In [0]:
ipl['win_by_wickets'].max()

10

In [0]:
ipl[ipl['win_by_wickets'] == 10]['winner']

2            Kolkata Knight Riders
34                 Kings XI Punjab
71                 Deccan Chargers
119               Delhi Daredevils
183    Royal Challengers Bangalore
298               Rajasthan Royals
376                 Mumbai Indians
390            Chennai Super Kings
542    Royal Challengers Bangalore
590            Sunrisers Hyderabad
Name: winner, dtype: object

In [0]:
ipl['toss_decision']=='bat'

NameError: ignored